### PR TITLE
Update for ru_ru

### PR DESCRIPTION
**Pull request by LEDshade**
Updating russian localization.

### CODE REVIEW

**Comment by TheIllusiveC4** [comment]
Thanks!

**Comment by LEDshade** [comment]
Well...  Unfortunately, the old ru_ru file wasn't changed to a new one in the newest version after merging. Yesterday, I tested 0.37 with new Russian localization and found out that it wasn't changed at all.

**Comment by LEDshade** [comment]
Снимок экрана 2021-08-03 221046

**Comment by LEDshade** [comment]
Снимок экрана 2021-08-03 221255

**Comment by LEDshade** [comment]
Снимок экрана 2021-08-03 221831

**Comment by TheIllusiveC4** [comment]
Oh I get it now, I didn't look at this properly. Sorry about that. The problem is that in the PR you put your file in the main folder instead of in the `src/main/resources/assets/diet/lang` folder. I'll fix it in a bit.

**Comment by LEDshade** [comment]
It's ok :) It's my mistake, too. If I named this file "NEW UPDATED ru_ru" instead of "ru_ru", it wouldn't be so confusing.

**Pull request merged**
